config/routes.rb
Rails.application.routes.draw do

  resources "contacts", only: [:new, :create]

  resources :categories

  resources :articles do
    resources :comments, only: [:create, :destroy, :update] #comments es sub_recurso de articles, pertenece a este.
  end

  devise_for :users
  root 'articles#index'

  get "/dashboard", to: "welcome#dashboard"
  put "/articles/:id/publish", to: "articles#publish" #Publicar es una accion q va a modificar un archivo ya existente asi q se usa el verbo o accion put para editar.
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :body, presence: true
  validates :body, presence: true, length: {minimum: 20}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy]
  before_action :set_article


  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.article, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @article, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:article_id])#Se puede acceder al recurso padre. 
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<article>
	<header class="text-right be-small">
		<%= time_ago_in_words(comment.created_at) %> ago - <%= link_to "Borrar", [@article,comment], method: :delete, class:"red" %> <!-- time_ago_in_words: helper. Muestra el tiempo desde q se creo el comentario -->
	</header>
	<div class="row">
		<div class="col-xs-1 col-md-1">
			<div class="box">
				<%= image_tag(comment.user.avatar) %> <!-- img del usuario -->
			</div>
		</div>
		<div class="col-xs-11 col-md-10">
			<div class="box">
				<%= comment.body %><!-- Muestra el cuerpo de comentario -->
			</div>
		</div>

	</div>
</article>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment], remote: true, html:{id:"comments-form", :"data-type"=>"
  json"}) do |f| %> <!--Formulario es generado por Recurso padre(article) y sub_recurso hijo(comment)--><!-- remote: true = Permite q el formulario se mande por AJAX -->
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
 

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>