config/routes.rb
Rails.application.routes.draw do

  resources "contacts", only: [:new, :create]

  resources :categories

  resources :articles do
    resources :comments, only: [:create, :destroy, :update] #comments es sub_recurso de articles, pertenece a este.
  end

  devise_for :users
  root 'articles#index'

  get "/dashboard", to: "welcome#dashboard"
  put "/articles/:id/publish", to: "articles#publish" #Publicar es una accion q va a modificar un archivo ya existente asi q se usa el verbo o accion put para editar.
end

app/models/article.rb
class Article < ActiveRecord::Base
	include AASM #Para q el modelo pueda hacer uso de las funciones de la maquina de estado.

	belongs_to :user #asociaciones, Un articulo pertenece a un usuario
	has_many :comments

	has_many :has_categories#Tabla intermedia creada por la relacion de muchos a muchos.
	has_many :categories, through: :has_categories#through: Atravez de.


	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: {minimum: 20}
	before_save :set_visits_count#Codigo en comun
	after_create :save_categories
	after_create :send_mail
	

	has_attached_file :cover, styles: { medium: "1280x720", thumb:"420x420" }#El archivo adjunto q se va a subir
	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/ #Por seguridad para evitar ataques, se descoge el formato de la img q se va a subir(VALIDACION)


	scope :publicados, ->{where(state: "published")} #Metodo de clase: Metodo q solo afecta a la clase no al objeto de este.
	scope :ultimos, ->{order("created_at DESC")} #Ordena los articulos por fecha de creacion los ultimos primero(Descendente).


	#Custom setter o atributo virtual
	def categories=(value)#setter: Es un metodo q permite asignarle valor al atributo de un objeto.
		@categories = value#Guarda en una variable el arreglo de categories.
	end

	def update_visits_count
		#self.save if self.visits_count.nil?#Si el contador de visitas es nil guardalo, esto activa before save
		self.update(visits_count: self.visits_count + 1)
	end


	aasm column: "state" do #state = La columna q va utilizar para controlar la maquina de estado.
	state :in_draft, initial: true #El estado inicial en q va estar el modelo es in_draft(en borrador).
	state :published

		event :publish do #Trancisiones entre los estados
			transitions from: :in_draft, to: :published #Pasa de draft a publicado
		end
		event :unpublish do
			transitions from: :published, to: :in_draft #Pasa de publicado a in_draft.
		end
	end


	private

	def send_mail
		ArticleMailer.new_article(self).deliver_later #deliver_latter: Permite ejecutar codigo asincrono.
	end
	def save_categories
		unless @categories.nil?#No hagas esto en caso de q esta condicion sea verdadero, a menos de q categorias sea nil haz esto
			@categories.each do |category_id|
				HasCategory.create(category_id: category_id, article_id: self.id)#self hace referencia al objeto con q se esta trabajo, este caso article.
			end
		end
	end

	def set_visits_count
		self.visits_count ||= 0 #Si es nil asignale este valor si no dejalo como esta
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#before_action :validate_user, except: [:show,:index]#CALLBACKS. Si el usuario no esta conectado redirijalo a iniciar session, excepto para show y index
	before_action :authenticate_user!, except: [:index,:show]#CALLBACKS DEVISE. Si el usuario no esta conectado redirijalo a iniciar session, excepto para show y index
	before_action :set_article, except: [:index,:new,:create] #Permite hacer refactor del codigo
	
	before_action :authenticate_editor!, only: [:new,:create,:update]#El usuario editor solo podra crear y eliminar.
	before_action :authenticate_admin!, only: [:destroy,:publish] #El usuario admin  podra eliminar.

	#GET /articles
	def index
		@articles = Article.paginate(page: params[:page],per_page:10).publicados.ultimos #Muestra todos los articulos en estado published(publicado) y ordenados por fecha de creaciond descendente.
		#Muestra 5 articulos por pagina.
		#paginate: metodo para paginar propip de la gema gem "will_paginate".
	end

	#GET /articles/:id
	def show
		
		@article.update_visits_count
		@comment = Comment.new #inicializacion de un nuevo comentario
	end

	#GET /articles/new
	def new
		@article = Article.new
		@categories = Category.all#Permite tener acceso a las categorias atraves del formulario de articles.
	end

	def edit
		
	end

	#POST /articles
	def create
		@article = current_user.articles.new(article_params)
		@article.categories = params[:categories]#Se le asigna los valores del arreglo de categories(categories[]) en el formulario de articles
		if @article.save #CONDICION DE LA VALIDACION DEL MODELO ARTICLE.
			redirect_to @article
		else
			render :new
		end
	end 

	#PUT /articles/:id
	def update
		if @article.update(article_params)
			redirect_to articles_path
		else
			render :edit
		end
	end

	#DELETE /articles/:idarticle_params
	def destroy
		
		@article.destroy
		redirect_to @article
	end
	
	def publish
		@article.publish! #Metodo q se utilizo en la consola para publicar
		redirect_to dashboard_path
	end
	

	private	
	
	def set_article
		@article = Article.find(params[:id])#Codigo en comun
	end

	def article_params
		params.require(:article).permit(:title,:body,:cover,:categories, :markup_body)
	end



end#FINAL

app/helpers/article_helper.rb
module ArticleHelper
end

app/views/articles/_article.html.erb
<div class="col-md-4 top-space">
	<div class="box relative article-height">
	<div class="absolute article-height background-cover" style="background:url(<%= article.cover.url(:thumb) %>);top:0px;left:0px;width:100%;background-size: cover;" > <!-- Add la img del cover del article en tamaño :thumb -->
		
	</div>
	<div class="absolute article-height background-cover" style="background:rgba(0,0,0,0.3);top:0px;left:0px;width:100%;" > <!-- Add la img del cover del article en tamaño :thumb -->
		
	</div>
	<div class="relative white text-center">
		<h2> <%= link_to article.title, article %></h2>		
		<p>
			<%= truncate(article.body,length:30) %> <!--truncate: helper metodo, corta una cadena y al fina de cada cadena asigna tres puntos-->
		</p> 
	</div>
	</div>
			
</div>

app/views/articles/_comments.html.erb
<div class="grey">
	<div class="row">
		<div class="col-xs-6">
			Participa en los comentarios
		</div>
		<div class="col-xs-6">
			<%= @article.comments.count  %>
			comentario(s)
		</div>
	</div>
	<div>
		<%= render "comments/form"%>  <!-- Me redirecciona al form de comments, para crear el comentario -->
	</div>
	<div class="to-space">
		<%= render @article.comments %> <!-- Render de coleccion, para mostrar los comentarios -->
	</div>
</div>

app/views/articles/_form.html.erb
<% name ||="Crear" %><!-- SI LA VARIABLE NO ESTA DEFINIDAD CREALA CON ESTE VALOR-->
<h1><%= name %> articulo</h1>
<%= form_for(@article, html: {id: "articles_form"}) do |f| %>
	<% @article.errors.full_messages.each do |message| %> <!-- ZONA DE ERRORES DE LAS VALIDACIONES A LA HORA DE CREAR UN ARTICULO --> 
		<div class="be-red white to-space">
			*<%= message %>
		</div>
	<%end%>
	<div class="field">
		<%= f.text_field :title, placeholder: "Titulo", class:"form-control"%>
	</div>
	<div class="field">
		Portada <%= f.file_field :cover %> <!-- Campo perteneciente a la img-->
	</div>
	<div class="field">
		<%= f.hidden_field :body, id:"body-textarea" %>
		<%= f.hidden_field :markup_body, id:"markup-body-textarea" %>
		<div id="epiceditor" style:"height:350px;"></div><!-- ID de EpicEditor, muestra el editor en la pagina -->
	</div>
	<div class="field">
		<label>Categorias</label>
		<% @categories.each do |category| %>
			<div class="field">
				<%= check_box_tag "categories[]", category.id %> <%= category.name %><!--Este control llena un arreglo q a la vez es su nombre(category[]), permite guardar las opciones seleccionadas en el arreglo -->
			</div>
		<%end%>
	</div>

	<div class="field">
		<%= f.submit "Guardar", class:"btn be-red white" %>
	</div>
<%end%>

<!-- Inicializacion de editor de epicEditor -->
<script>

	var editor = new EpicEditor({
		textarea :"markup-body-textarea",
		file:{
			name:"nuevo_articulo"
		}
	});
	editor.load();
	
	$("#articles_form").on("submit",function(){
		$("#body-textarea").val( editor.exportFile("nuevo_articulo", "html"));
		$("#markup-body-textarea").val( editor.exportFile("nuevo_articulo"));
	});

</script>

app/views/articles/edit.html.erb
<div style="width:80%;margin:0 auto;">
	<%= render "form", name: "Editar" %>
</div>

app/views/articles/index.html.erb
<div class="container" style="margin:0 auto;">
	<h1>Articulos</h1>
	<div class="row">
		<%= render @articles %> <!-- Se le pasa una coleccion en vez de un partial--><!-- Cuando al metodo "render" se le pasa un arreglo del modelo de la BD este itera sobre el arreglo(coleccion) como lo haria < % = @articles.each do |article| %> -->
	</div>
	<div class="top-space text-center">
	<%= will_paginate @articles %> <!-- hellper de will_paginate. Muestra controles para moverse entre las paginas -->	
	</div>
</div>

app/views/articles/new.html.erb
<div style="width:80%;margin:0 auto;">
	<%= render "form"%>
</div>

app/views/articles/show.html.erb
<article class="botton-space"> 
	<%= article_cover @article.cover.url %><!-- article_cover: nombre del metodo helpers -->
	<div class="row center-xs">
		<div class="col-xs-12 ligth-border col-md-7">
			<h1 class="be-big blue"><%= @article.title %></h1>			
				<p class="text-right be-small">
					<%= link_to "Atras", articles_path, class:"underline" %> - 
					<span class="red"><%=  @article.visits_count %> visita(s)</span> - 
					<% unless @article.user.nil? %>
						Escrito por: <%= @article.user.email %>
					<%end%>
				</p>
			<div class="text-justify">
				<%= Sanitize.fragment(@article.body, Sanitize::Config::RELAXED).html_safe  %> <!-- html_safe: Muestra la informacion con el marcado de EpicEdictor--> <!--Sanitize: Limpia este fragmento, quita los scripts -->
			</div>
			<div class="to-space">
				<%= render "articles/comments" %> <!--Me muestra los comentarios -->
			</div>
		</div>
	</div>
</article>>

app/views/articles/showBorrador.html.erb
<h1><%= @article.title %></h1>
<% unless @article.user.nil? %>
	<p>
		Escrito por: <%= @article.user.email %>
	</p>
<%end%>

<div class="field"><!-- Muestra las categorias a las q pertenece ese articulo f-->
	<% @article.categories.each do |category|%>
		<%= link_to category.name, category, style:"color:#{category.color}" %>
	<%end%>
</div>
<div class="field">
	<%= image_tag @article.cover.url(:thumb) %><!-- Genera un elemento imagen en tamaño pequeño-->
</div>
<p>
	Visitas: <%= @article.visits_count %> 
</p>
<div>
	<%= Sanitize.fragment(@article.body, Sanitize::Config::RELAXED).html_safe  %> <!-- Muestra la informacion con el marcado de EpicEdictor--> <!-- Limpia este fragmento, quita los scripts -->
</div>
<div class="field">
	<h3>Comentarios</h3>
	<%= render "comments/form" %> <!-- Me redirecciona al form de comments, para crear el comentario -->
	<ul id="comments-box">
		<% @article.comments.each do |comment| %>
			<li>
				<%= comment.body %> - <%= comment.user.email %><!-- Muestra el comentario y usuario q lo creo -->			
			</li>			
		<%end%>
	</ul>
</div>
<div>
	<%= link_to "Editar", edit_article_path(@article) %>
</div>