config/routes.rb
Rails.application.routes.draw do

  resources "contacts", only: [:new, :create]

  resources :categories

  resources :articles do
    resources :comments, only: [:create, :destroy, :update] #comments es sub_recurso de articles, pertenece a este.
  end

  devise_for :users
  root 'articles#index'

  get "/dashboard", to: "welcome#dashboard"
  put "/articles/:id/publish", to: "articles#publish" #Publicar es una accion q va a modificar un archivo ya existente asi q se usa el verbo o accion put para editar.
end

app/views/partial/_navigation.html.erb
<header>
	<nav class="be-red white large-padding">	
		<ul class="no-list row center-xs middle-xs">
			<li class="col-md">
				<h1 class="no-margin" id="logo"><%= link_to "Blog facilito", root_path %> </h1>
			</li>
			<li class="col-md">
				<%= link_to "Articulos", articles_path %>
			</li>
			<% @categories.each do |category| %> <!-- Me muestra las diferentes category-->
				<li class="col-md">
					<%= link_to category.name, category %><!-- Me redirije al show de ese category-->
				</li>
			<%end%>
			
			
			<% if user_signed_in? %> <!-- SI EL USUARIO ESTA CONECTADO HAGA-->
				<li class="col-md">
					<%= link_to "Cerrar sesion", destroy_user_session_path, method: :delete %>
				</li>
			<%else%>
				<li class="col-md">
					<%= link_to "Iniciar sesion", new_user_session_path %><!--User: Corresponde al modelo q se creo con devise -->
				</li>
				<li class="col-md">
					<%= link_to "Crear cuenta", new_user_registration_path %><!-- -->
				</li>
			<% end %>
		</ul>	
	</nav>
</header>